/* Generated by AN DISI Unibo */ 
package it.unibo.callermock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Callermock ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
<<<<<<< HEAD
						CommUtils.outblue("$name | start ")
						 var V = "2.0"  
=======
						CommUtils.outgreen("$name | start ")
						 var V = "2.0"  
						forward("eval", "arg($V)" ,"sistemas" ) 
>>>>>>> c08e98b10c1bf8dd57e9105106fa9dd95b91740e
						request("evalr", "argr($V)" ,"sistemas" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
<<<<<<< HEAD
					 transition(edgeName="t02",targetState="handleReply",cond=whenReply("evalreply"))
=======
					 transition(edgeName="t06",targetState="handleReply",cond=whenReply("evalreply"))
>>>>>>> c08e98b10c1bf8dd57e9105106fa9dd95b91740e
				}	 
				state("handleReply") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("value(V)"), Term.createTerm("value(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val VasString = payloadArg(0)  
								CommUtils.outmagenta("$name | result received=$VasString")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
