/* Generated by AN DISI Unibo */ 
package it.unibo.sistemas

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sistemas ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
<<<<<<< HEAD
				fun eval(x: Double): String{ 
				 val R = 3*x
				 return ""+R
			}
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("Hello world")
						 val V = eval(2.0)  
						CommUtils.outblue("result = $V")
						CommUtils.outblack("now i am waiting for a dispatch")
=======
				fun eval(x: Double): String {
				   val R = 3*x
				   return ""+R
				}
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("Hello world")
						 val V = eval(2.0)  
						CommUtils.outblue("result=$V")
						CommUtils.outblack("now I'm waiting for a dispatch or request")
>>>>>>> c08e98b10c1bf8dd57e9105106fa9dd95b91740e
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
<<<<<<< HEAD
					 transition(edgeName="t00",targetState="handleeval",cond=whenDispatch("eval"))
					transition(edgeName="t01",targetState="handleRequest",cond=whenRequest("evalr"))
				}	 
				state("handleeval") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outmagenta("$name | msg=$currentMsg")
						if( checkMsgContent( Term.createTerm("arg(V)"), Term.createTerm("arg(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val VasString = payloadArg(0)
												val V = VasString.toDouble()
												
								CommUtils.outgreen("$name | evaluate $V")
								 val R = eval(V) 
								CommUtils.outgreen("$name | result= $R")
=======
					 transition(edgeName="t00",targetState="handleEval",cond=whenDispatch("eval"))
					transition(edgeName="t01",targetState="handleRequest",cond=whenRequest("evalr"))
				}	 
				state("handleEval") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outmagenta("$name | currentMsg=$currentMsg")
						if( checkMsgContent( Term.createTerm("arg(V)"), Term.createTerm("arg(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val VasString = payloadArg(0)  
											   val V         = VasString.toDouble()
								CommUtils.outgreen("$name | evauate $V")
								 val R = eval(V)  
								CommUtils.outmagenta("$name | result=$R")
>>>>>>> c08e98b10c1bf8dd57e9105106fa9dd95b91740e
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
<<<<<<< HEAD
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
=======
					 transition(edgeName="t02",targetState="handleEval",cond=whenDispatch("eval"))
					transition(edgeName="t03",targetState="handleRequest",cond=whenRequest("evalr"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
>>>>>>> c08e98b10c1bf8dd57e9105106fa9dd95b91740e
						 	   
						 var R = ""  
						if( checkMsgContent( Term.createTerm("argr(V)"), Term.createTerm("argr(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
<<<<<<< HEAD
								
												val VasString = payloadArg(0)
												val V = VasString.toDouble()
												
								CommUtils.outblue("$name | evaluate $V")
								 R = eval(V) 
								CommUtils.outblue("$name | result= $R")
=======
								 val VasString = payloadArg(0) 
											   val V         = VasString.toDouble()
								CommUtils.outblue("$name | evauate $V")
								 R = eval(V)  
								CommUtils.outblue("$name | result=$R")
>>>>>>> c08e98b10c1bf8dd57e9105106fa9dd95b91740e
						}
						answer("evalr", "evalreply", "value($R)"   )  
						CommUtils.outblue("$name | handleRequest ends")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
<<<<<<< HEAD
=======
					 transition(edgeName="t04",targetState="handleEval",cond=whenDispatch("eval"))
					transition(edgeName="t05",targetState="handleRequest",cond=whenRequest("evalr"))
>>>>>>> c08e98b10c1bf8dd57e9105106fa9dd95b91740e
				}	 
			}
		}
} 
